logging:
  level:
    com.nancologist.car360: ${LOGGING_LEVEL_COM_NANCOLOGIST_CAR360}
#    root: ${LOGGING_LEVEL_ROOT}

spring:

  liquibase:
    change-log: ${SPRING_LIQUIBASE_CHANGE_LOG}
    default-schema: car360
    enabled: ${SPRING_LIQUIBASE_ENABLED}

  application:
    name: car360

  security:
    jwtSecret: ${SPRING_SECURITY_JWTSECRET}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        default_schema: car360
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

    show-sql: ${SPRING_JPA_SHOW_SQL}

  output:
    ansi:
      enabled: always
