spring:
  application:
    name: car360

  datasource:
    url: jdbc:postgresql://localhost:5432/springular
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: car360
        format_sql: true # Optional: Formats SQL for better readability
    hibernate:
      ddl-auto: update
      org:
        hibernate:
          SQL: DEBUG
    show-sql: true # Optional: Logs SQL queries
