spring:
  application:
    name: my-rest-app

  datasource:
    url: jdbc:postgresql://localhost:5432/springular
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: car360
        format_sql: true # Optional: Formats SQL for better readability
    hibernate:
      ddl-auto: update
    show-sql: true # Optional: Logs SQL queries
