logging:
  level:
    com.nancologist.car360: TRACE
#    root: TRACE

spring:

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: car360
    enabled: true

  application:
    name: car360

  security:
    jwtSecret: AVeryStrongKeyToGenerateJwtTokensss2313138989011

  datasource:
    url: jdbc:postgresql://localhost:5432/springular
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: car360
        format_sql: true # Optional: Formats SQL for better readability
    hibernate:
      ddl-auto: validate
      org:
        hibernate:
          SQL: DEBUG
    show-sql: true # Optional: Logs SQL queries

  output:
    ansi:
      enabled: always # Get colorful output in Terminal!
